---

apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: mock-email-service
  namespace: mock-service
spec:
  selector:
    # Selector for Pods
    app: mock-email-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
