---

- name: Update apt packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Debian utilities
  ansible.builtin.apt:
    state: present
    name:
      - git
      - maven