---

- name: Update dnf packages
  become: true
  ansible.builtin.dnf:
    update_cache: true
    state: latest
    use_backend: dnf4

- name: Install RedHat utilities
  ansible.builtin.dnf:
    state: present
    use_backend: dnf4
    name:
      - git
      - maven