{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
      "ec2:AttachVolume",
      "ec2:DeleteVolume",
      "ec2:DescribeAvailabilityZones",
      "ec2:DescribeInstances",
      "ec2:DescribeTags",
      "ec2:DescribeVolumes",
      "ec2:DetachVolume",
      "route53:ListHostedZones",
      "route53:ListResourceRecordSets",
      "iam:ListUsers",
      "iam:GetGroup",
      "s3:DeleteObject",
      "s3:GetAccessPoint",
      "s3:GetBucketAcl",
      "s3:GetBucketCORS",
      "s3:GetBucketLocation",
      "s3:GetBucketLogging",
      "s3:GetBucketPolicy",
      "s3:GetObject",
      "s3:GetObjectVersion",
      "s3:ListAllMyBuckets",
      "s3:ListBucket",
      "s3:ListBucketVersions",
      "s3:PutObject",
      "ecr:BatchGetImage",
      "ecr:BatchCheckLayerAvailability",
      "ecr:CompleteLayerUpload",
      "ecr:GetDownloadUrlForLayer",
      "ecr:InitiateLayerUpload",
      "ecr:PutImage",
      "ecr:UploadLayerPart",
      "ecr:GetAuthorizationToken",
      "ecr:DescribeRepositories",
      "ecr:DescribeImages",
      "ecr:ListImages",
      "ecr:ListTagsForResource",
      "ecr:DescribeImageScanFindings",
      "ecs:DescribeTaskDefinition",
      "ecs:RegisterContainerInstance",
			"ecs:DiscoverPollEndpoint",
			"ecs:UpdateContainerInstancesState",
			"ecs:Submit*",
			"ecs:StartTelemetrySession",
			"ecs:Poll",
			"ecs:DeregisterContainerInstance",
      "logs:PutLogEvents",
			"logs:CreateLogStream"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}