- name: Update dnf packages
  become: true
  ansible.builtin.dnf:
    update_cache: true
    state: latest
    use_backend: dnf4

- name: Install RedHat utilities
  ansible.builtin.dnf:
    state: present
    use_backend: dnf4
    name:
      - python3
      - python3-pip
      - collectd
      - chrony
      - unzip
      - wget
      - jq
      - nettools
      - java-22-amazon-corretto-headless
      - java-22-amazon-corretto-devel

- name: Ensure chrony is running
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true

# Reboot after python3-pip
- name: Restart server
  ansible.builtin.command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true

- name: Check the Uptime of the servers
  ansible.builtin.shell: "uptime"
  register: uptime

- name: Show uptime
  ansible.builtin.debug: var=uptime
