---

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Configure RedHat + CentOS Specific Tasks
  ansible.builtin.import_tasks: configure-redhat-centos.yml
  when: ansible_facts['os_family']|lower == 'redhat' and ansible_facts['distribution']|lower == 'centos'

- name: Configure RedHat + Amazon Linux 2023 Specific Tasks
  ansible.builtin.import_tasks: configure-redhat-al2023.yml
  when: ansible_facts['os_family']|lower == 'redhat' and ansible_facts['distribution']|lower == 'amazon'

- name: Configure Debian OS Specific Tasks
  ansible.builtin.import_tasks: configure-debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
