---

- name: Configure RedHat + CentOS Specific Tasks
  ansible.builtin.import_tasks: configure-redhat-centos.yml
  when: ansible_facts['os_family']|lower == 'redhat' and ansible_facts['distribution']|lower == 'centos'

- name: Configure RedHat + Amazon Linux 2023 Specific Tasks
  ansible.builtin.import_tasks: configure-redhat-al2023.yml
  when: ansible_facts['os_family']|lower == 'redhat' and ansible_facts['distribution']|lower == 'amazon'

- name: Configure debian
  ansible.builtin.include_tasks: configure-debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure /etc/docker/ directory exists.
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0755'
  when: docker_daemon_options.keys() | length > 0

- name: Configure Docker daemon options.
  ansible.builtin.copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: '0644'
  when: docker_daemon_options.keys() | length > 0
  notify: Restart docker

- name: Ensure Docker is started and enabled at boot.
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create "docker" group
  ansible.builtin.group:
    name: "{{ docker_group }}"
    state: present
  become: true

- name: Post install redhat
  ansible.builtin.include_tasks: post-install-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Post install debian
  ansible.builtin.include_tasks: post-install-debian.yml
  when: ansible_os_family == 'Debian'

- name: Reset ssh connection to allow user changes to affect remote user
  ansible.builtin.meta:
    reset_connection

- name: Log completion
  ansible.builtin.command: echo "Docker installation steps are complete!"
  changed_when: false
