---

- name: Add remote user to "docker" group
  ansible.builtin.shell: "usermod -aG {{ docker_group }} {{ docker_debian_user }}"
  args:
    executable: /bin/bash
  become: true
  changed_when: false
